services:
  - type: web
    name: yt-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_IDS
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false

  - type: worker
    name: yt-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_IDS
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
